### ISSUE TITLE
Feature Request: Dashboard tab does not show actions from API calls

### ISSUE THREAD

**Issue by ifuratdev** [luyadev/luya-module-admin#349] opened 2019-08-21 14:06 UTC
Feature Request:
Dashboard tab does not show actions from API calls

For example when adding a new Addessbook/Contact
The Addressbook Dashboard tab doesn't show this action in the list dashboard list

**Comment by nadar** [comment] 2019-08-21 14:42
this is not a bug, this is an expected behavior. Otherwise for system with 1000 of api calls the dashboard would lose its idea of display data from users. In order to view the activity of an api user, check the history active window.

---

btw. if you don't provide the informations from issue template, please at least take the time to remove those informations. If you expected help, take time to format and create your issues properly...

**Comment by ifuratdev** [comment] 2019-08-21 15:53
noted.
I have updated the request to be feature request

**Comment by nadar** [comment] 2019-08-21 16:16
So we can close the issue?

**Comment by ifuratdev** [comment] 2019-08-21 16:28
in this case the API call is coming from another application. 
The other application is calling the luya application to create new records. 
We need to be able to see records created from the api calls in the dashboard.

Can this be done as an option?

**Comment by nadar** [comment] 2019-08-21 20:31
sure, we could enable this as option. would you like to send a PR?

**Comment by ifuratdev** [comment] 2019-08-22 12:09
Sure I will, but this is not a top priority for me now

**Comment by nadar** [comment] 2020-04-29 10:40
With release of luya admin version 3.2 you are able to configure: dashboardLogDisplayApiUserData = true

**Closed** 2020-04-29 10:39 UTC
Labels: enhancement
